services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Q9e5CGhwTYVhlt1
      - POSTGRES_DB=restaurant
      - QRIS_STATIC=${QRIS_STATIC}
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurant-network

  web:
    build: .
    ports:
      - "5009:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:Q9e5CGhwTYVhlt1@db:5432/restaurant
    networks:
      - restaurant-network

volumes:
  postgres_data:

networks:
  restaurant-network:
    driver: bridge