services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Q9e5CGhwTYVhlt1
      POSTGRES_DB: restaurant
      QRIS_STATIC: "00020101021126650013ID.CO.BCA.WWW011893600014000299749202150008850029974920303UKE51440014ID.CO.QRIS.WWW0215ID10254011522240303UKE5204581453033605802ID5918DAPUR ANTAR 24 JAM6015JAKARTA SELATAN61051263062070703A0163042B58"
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurant-network

  web:
    build: .
    ports:
      - "5009:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:Q9e5CGhwTYVhlt1@db:5432/restaurant
    networks:
      - restaurant-network

volumes:
  postgres_data:

networks:
  restaurant-network:
    driver: bridge